-- =====================================================================
--  규격/규제 정보 관리 DDL  /  Oracle 11g 이상
--
--  설계문서: docs/규격규제_정보관리_설계.md
--  테이블 4개
--    1. REG_INFO          정보 레코드 (마스터)
--    2. REG_INFO_TARGET   타겟 (규제/규격/사업부/제품군/제품/권역/국가 - 멀티셀렉트)
--    3. REG_INFO_HIST     변경 이력 (수정 = 새 VERSION INSERT + 스냅샷)
--    4. REG_CONFLICT_HIST 충돌 이력 (저장 직전 판정 결과와 담당자 조치)
--
--  첨부는 별도 테이블을 만들지 않고 기존 파일 관리 모듈의
--  파일그룹 ID(ATTACH_GROUP_ID)로 연계한다.
-- =====================================================================

-- ---------------------------------------------------------------------
-- DROP (개발 편의. 운영 반영 시 제거)
-- ---------------------------------------------------------------------
-- DROP TABLE REG_CONFLICT_HIST CASCADE CONSTRAINTS;
-- DROP TABLE REG_INFO_HIST     CASCADE CONSTRAINTS;
-- DROP TABLE REG_INFO_TARGET   CASCADE CONSTRAINTS;
-- DROP TABLE REG_INFO          CASCADE CONSTRAINTS;
-- DROP SEQUENCE SEQ_REG_INFO;
-- DROP SEQUENCE SEQ_REG_INFO_TARGET;
-- DROP SEQUENCE SEQ_REG_INFO_HIST;
-- DROP SEQUENCE SEQ_REG_CONFLICT_HIST;


-- ---------------------------------------------------------------------
-- 1. REG_INFO : 정보 레코드 (규제 1건 = 1행)
--    멀티 선택 항목은 전부 REG_INFO_TARGET 으로 분리한다.
--    분야(FIELD_CD)만 단일 값이므로 마스터에 둔다.
-- ---------------------------------------------------------------------
CREATE TABLE REG_INFO (
    REG_INFO_ID     NUMBER(19)      NOT NULL,
    REG_NO          VARCHAR2(30)    NOT NULL,
    TITLE           VARCHAR2(300)   NOT NULL,
    FIELD_CD        VARCHAR2(30)    NOT NULL,
    MARK_NM         VARCHAR2(200),
    AUTHORITY       VARCHAR2(200),
    URL             VARCHAR2(1000),
    SUMMARY         CLOB,
    ATTACH_GROUP_ID VARCHAR2(50),
    STATUS_CD       VARCHAR2(20)    DEFAULT 'DRAFT' NOT NULL,
    VERSION_NO      NUMBER(5)       DEFAULT 1 NOT NULL,
    EFFECTIVE_DT    DATE,
    EXPIRE_DT       DATE,
    PARENT_INFO_ID  NUMBER(19),
    USE_YN          CHAR(1)         DEFAULT 'Y' NOT NULL,
    REG_ID          VARCHAR2(50),
    REG_DT          DATE            DEFAULT SYSDATE NOT NULL,
    UPD_ID          VARCHAR2(50),
    UPD_DT          DATE,
    CONSTRAINT PK_REG_INFO PRIMARY KEY (REG_INFO_ID),
    CONSTRAINT UK_REG_INFO_NO UNIQUE (REG_NO),
    CONSTRAINT CK_REG_INFO_STATUS CHECK (STATUS_CD IN ('DRAFT','REVIEW','ACTIVE','EXPIRED')),
    CONSTRAINT CK_REG_INFO_USE CHECK (USE_YN IN ('Y','N')),
    CONSTRAINT FK_REG_INFO_PARENT FOREIGN KEY (PARENT_INFO_ID) REFERENCES REG_INFO (REG_INFO_ID)
);
COMMENT ON TABLE  REG_INFO                 IS '규격/규제 정보 레코드';
COMMENT ON COLUMN REG_INFO.REG_NO          IS '업무 규제번호 (예: REG-2026-0001)';
COMMENT ON COLUMN REG_INFO.TITLE           IS '규제 제목';
COMMENT ON COLUMN REG_INFO.FIELD_CD        IS '분야 코드 (SAFETY/EMC/RF/ENERGY/ENV/RECYCLE/LABEL/BROADCAST/CHEM/ACCESS)';
COMMENT ON COLUMN REG_INFO.MARK_NM         IS '인증마크·표시 (예: KC 마크 + 안전확인신고번호)';
COMMENT ON COLUMN REG_INFO.AUTHORITY       IS '소관 기관';
COMMENT ON COLUMN REG_INFO.URL             IS '근거 법령·고시 URL';
COMMENT ON COLUMN REG_INFO.SUMMARY         IS '준수 요건 요약';
COMMENT ON COLUMN REG_INFO.ATTACH_GROUP_ID IS '첨부 파일그룹 ID (파일 관리 모듈 연계)';
COMMENT ON COLUMN REG_INFO.STATUS_CD       IS '상태 (DRAFT/REVIEW/ACTIVE/EXPIRED)';
COMMENT ON COLUMN REG_INFO.VERSION_NO      IS '현재 버전. 수정 시 +1 하고 REG_INFO_HIST 에 스냅샷 INSERT';
COMMENT ON COLUMN REG_INFO.PARENT_INFO_ID  IS '충돌 조치 결과 상위로 편입된 레코드 ID (하위 예외/특례일 때 세팅)';

CREATE INDEX IX_REG_INFO_01 ON REG_INFO (FIELD_CD, STATUS_CD);
CREATE INDEX IX_REG_INFO_02 ON REG_INFO (EFFECTIVE_DT);

CREATE SEQUENCE SEQ_REG_INFO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_REG_INFO_ID
BEFORE INSERT ON REG_INFO FOR EACH ROW
WHEN (NEW.REG_INFO_ID IS NULL)
BEGIN
    SELECT SEQ_REG_INFO.NEXTVAL INTO :NEW.REG_INFO_ID FROM DUAL;
END;
/


-- ---------------------------------------------------------------------
-- 2. REG_INFO_TARGET : 멀티 셀렉트 대상
--    TARGET_TYPE 으로 7종을 한 테이블에 수용한다.
--    LEVEL_NO 는 충돌 판정 시 상·하위 비교의 기준이 된다.
--       권역(1) > 국가(2)
--       사업부(1) > 제품군(2) > 제품(3)
--       규제(1) > 규격(2)
-- ---------------------------------------------------------------------
CREATE TABLE REG_INFO_TARGET (
    TARGET_ID       NUMBER(19)      NOT NULL,
    REG_INFO_ID     NUMBER(19)      NOT NULL,
    TARGET_TYPE     VARCHAR2(20)    NOT NULL,
    TARGET_CD       VARCHAR2(50)    NOT NULL,
    TARGET_NM       VARCHAR2(200),
    PARENT_TARGET_CD VARCHAR2(50),
    LEVEL_NO        NUMBER(2)       DEFAULT 1 NOT NULL,
    EXCLUDE_YN      CHAR(1)         DEFAULT 'N' NOT NULL,
    SORT_ORDER      NUMBER(5)       DEFAULT 0 NOT NULL,
    REG_ID          VARCHAR2(50),
    REG_DT          DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_REG_INFO_TARGET PRIMARY KEY (TARGET_ID),
    CONSTRAINT UK_REG_INFO_TARGET UNIQUE (REG_INFO_ID, TARGET_TYPE, TARGET_CD),
    CONSTRAINT CK_REG_TARGET_TYPE CHECK (TARGET_TYPE IN
        ('REGULATION','STANDARD','DIVISION','PRODUCT_GROUP','PRODUCT','REGION','COUNTRY')),
    CONSTRAINT CK_REG_TARGET_EXCL CHECK (EXCLUDE_YN IN ('Y','N')),
    CONSTRAINT FK_REG_TARGET_INFO FOREIGN KEY (REG_INFO_ID)
        REFERENCES REG_INFO (REG_INFO_ID) ON DELETE CASCADE
);
COMMENT ON TABLE  REG_INFO_TARGET                  IS '규제 정보 적용 대상 (멀티 셀렉트)';
COMMENT ON COLUMN REG_INFO_TARGET.TARGET_TYPE      IS '대상 구분 (REGULATION/STANDARD/DIVISION/PRODUCT_GROUP/PRODUCT/REGION/COUNTRY)';
COMMENT ON COLUMN REG_INFO_TARGET.TARGET_CD        IS '공통코드 값';
COMMENT ON COLUMN REG_INFO_TARGET.TARGET_NM        IS '조회 성능용 비정규화 명칭';
COMMENT ON COLUMN REG_INFO_TARGET.PARENT_TARGET_CD IS '상위 코드 (국가→권역, 제품→제품군, 규격→규제)';
COMMENT ON COLUMN REG_INFO_TARGET.LEVEL_NO         IS '계층 레벨. 충돌 판정 시 상·하위 비교 기준';
COMMENT ON COLUMN REG_INFO_TARGET.EXCLUDE_YN       IS 'Y = 이 대상은 적용 범위에서 제외 (충돌 조치 EXCLUDE 결과)';

CREATE INDEX IX_REG_TARGET_01 ON REG_INFO_TARGET (TARGET_TYPE, TARGET_CD);
CREATE INDEX IX_REG_TARGET_02 ON REG_INFO_TARGET (REG_INFO_ID, TARGET_TYPE);

CREATE SEQUENCE SEQ_REG_INFO_TARGET START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_REG_INFO_TARGET_ID
BEFORE INSERT ON REG_INFO_TARGET FOR EACH ROW
WHEN (NEW.TARGET_ID IS NULL)
BEGIN
    SELECT SEQ_REG_INFO_TARGET.NEXTVAL INTO :NEW.TARGET_ID FROM DUAL;
END;
/


-- ---------------------------------------------------------------------
-- 3. REG_INFO_HIST : 변경 이력
--    수정할 때마다 마스터 + 타겟 전체를 JSON 스냅샷으로 남긴다.
--    (타겟이 멀티행이라 컬럼 단위 diff 만으로는 복원이 안 됨)
-- ---------------------------------------------------------------------
CREATE TABLE REG_INFO_HIST (
    HIST_ID         NUMBER(19)      NOT NULL,
    REG_INFO_ID     NUMBER(19)      NOT NULL,
    VERSION_NO      NUMBER(5)       NOT NULL,
    CHANGE_TYPE     VARCHAR2(20)    NOT NULL,
    CHANGE_NOTE     VARCHAR2(1000),
    SNAPSHOT_JSON   CLOB,
    CONFLICT_ID     NUMBER(19),
    REG_ID          VARCHAR2(50),
    REG_DT          DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_REG_INFO_HIST PRIMARY KEY (HIST_ID),
    CONSTRAINT UK_REG_INFO_HIST UNIQUE (REG_INFO_ID, VERSION_NO, CHANGE_TYPE),
    CONSTRAINT CK_REG_HIST_TYPE CHECK (CHANGE_TYPE IN
        ('INSERT','UPDATE','DELETE','CONFLICT_RESOLVE')),
    CONSTRAINT FK_REG_HIST_INFO FOREIGN KEY (REG_INFO_ID)
        REFERENCES REG_INFO (REG_INFO_ID) ON DELETE CASCADE
);
COMMENT ON TABLE  REG_INFO_HIST               IS '규제 정보 변경 이력 (수정 = 새 버전 INSERT)';
COMMENT ON COLUMN REG_INFO_HIST.CHANGE_TYPE   IS 'INSERT/UPDATE/DELETE/CONFLICT_RESOLVE';
COMMENT ON COLUMN REG_INFO_HIST.SNAPSHOT_JSON IS '해당 버전의 마스터+타겟 전체 스냅샷 JSON';
COMMENT ON COLUMN REG_INFO_HIST.CONFLICT_ID   IS '충돌 조치로 생긴 이력이면 REG_CONFLICT_HIST 참조';

CREATE INDEX IX_REG_HIST_01 ON REG_INFO_HIST (REG_INFO_ID, VERSION_NO DESC);

CREATE SEQUENCE SEQ_REG_INFO_HIST START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_REG_INFO_HIST_ID
BEFORE INSERT ON REG_INFO_HIST FOR EACH ROW
WHEN (NEW.HIST_ID IS NULL)
BEGIN
    SELECT SEQ_REG_INFO_HIST.NEXTVAL INTO :NEW.HIST_ID FROM DUAL;
END;
/


-- ---------------------------------------------------------------------
-- 4. REG_CONFLICT_HIST : 충돌 이력
--    저장 직전 판정 결과 + 담당자가 고른 조치를 그대로 적재한다.
--    판정 방향은 항상 "신규 레코드 기준".
--      PARENT  = 신규가 기존의 상위 (신규 유럽 ⊃ 기존 프랑스)
--      CHILD   = 신규가 기존의 하위 (신규 프랑스 ⊂ 기존 유럽)
--      SAME    = 범위 완전 동일
--      OVERLAP = 포함관계 없이 일부만 겹침
-- ---------------------------------------------------------------------
CREATE TABLE REG_CONFLICT_HIST (
    CONFLICT_ID     NUMBER(19)      NOT NULL,
    NEW_REG_INFO_ID NUMBER(19),
    NEW_REG_NO      VARCHAR2(30),
    EXIST_REG_INFO_ID NUMBER(19)    NOT NULL,
    EXIST_REG_NO    VARCHAR2(30),
    CONFLICT_TYPE   VARCHAR2(20)    NOT NULL,
    CONFLICT_AXIS   VARCHAR2(20)    NOT NULL,
    NEW_SCOPE_TXT   VARCHAR2(1000),
    EXIST_SCOPE_TXT VARCHAR2(1000),
    DETAIL_JSON     CLOB,
    DECISION_CD     VARCHAR2(20),
    DECISION_NOTE   VARCHAR2(1000),
    STATUS_CD       VARCHAR2(20)    DEFAULT 'DETECTED' NOT NULL,
    DETECT_DT       DATE            DEFAULT SYSDATE NOT NULL,
    DECIDE_ID       VARCHAR2(50),
    DECIDE_DT       DATE,
    CONSTRAINT PK_REG_CONFLICT_HIST PRIMARY KEY (CONFLICT_ID),
    CONSTRAINT CK_REG_CONF_TYPE CHECK (CONFLICT_TYPE IN ('SAME','PARENT','CHILD','OVERLAP')),
    CONSTRAINT CK_REG_CONF_AXIS CHECK (CONFLICT_AXIS IN ('GEO','ORG','RULE')),
    CONSTRAINT CK_REG_CONF_DECISION CHECK (DECISION_CD IN
        ('KEEP_BOTH','MERGE','EXCLUDE','REPLACE','CANCEL')),
    CONSTRAINT CK_REG_CONF_STATUS CHECK (STATUS_CD IN ('DETECTED','RESOLVED','IGNORED')),
    CONSTRAINT FK_REG_CONF_EXIST FOREIGN KEY (EXIST_REG_INFO_ID)
        REFERENCES REG_INFO (REG_INFO_ID)
);
COMMENT ON TABLE  REG_CONFLICT_HIST                 IS '규제 정보 충돌 판정/조치 이력';
COMMENT ON COLUMN REG_CONFLICT_HIST.NEW_REG_INFO_ID IS '신규(저장 시도) 레코드 ID. 등록 취소 시 NULL';
COMMENT ON COLUMN REG_CONFLICT_HIST.NEW_REG_NO      IS '등록 취소된 건도 추적하기 위한 규제번호 스냅샷';
COMMENT ON COLUMN REG_CONFLICT_HIST.CONFLICT_TYPE   IS 'SAME/PARENT/CHILD/OVERLAP (신규 레코드 기준)';
COMMENT ON COLUMN REG_CONFLICT_HIST.CONFLICT_AXIS   IS '충돌 축 GEO(권역/국가) / ORG(사업부·제품군·제품) / RULE(규제·규격)';
COMMENT ON COLUMN REG_CONFLICT_HIST.DETAIL_JSON     IS '축별 판정 상세 (EQUAL/SUPERSET/SUBSET/OVERLAP)';
COMMENT ON COLUMN REG_CONFLICT_HIST.DECISION_CD     IS 'KEEP_BOTH/MERGE/EXCLUDE/REPLACE/CANCEL';
COMMENT ON COLUMN REG_CONFLICT_HIST.STATUS_CD       IS 'DETECTED(판정만)/RESOLVED(조치완료)/IGNORED(등록취소)';

CREATE INDEX IX_REG_CONF_01 ON REG_CONFLICT_HIST (EXIST_REG_INFO_ID);
CREATE INDEX IX_REG_CONF_02 ON REG_CONFLICT_HIST (NEW_REG_INFO_ID);
CREATE INDEX IX_REG_CONF_03 ON REG_CONFLICT_HIST (STATUS_CD, DETECT_DT);

CREATE SEQUENCE SEQ_REG_CONFLICT_HIST START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_REG_CONFLICT_HIST_ID
BEFORE INSERT ON REG_CONFLICT_HIST FOR EACH ROW
WHEN (NEW.CONFLICT_ID IS NULL)
BEGIN
    SELECT SEQ_REG_CONFLICT_HIST.NEXTVAL INTO :NEW.CONFLICT_ID FROM DUAL;
END;
/


-- ---------------------------------------------------------------------
-- 조회 편의 뷰 : 목록 그리드 1행 = 이 뷰 1행
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW V_REG_INFO_LIST AS
SELECT  I.REG_INFO_ID,
        I.REG_NO,
        I.TITLE,
        I.FIELD_CD,
        I.MARK_NM,
        I.URL,
        I.STATUS_CD,
        I.VERSION_NO,
        I.EFFECTIVE_DT,
        (SELECT LISTAGG(T.TARGET_NM, ', ') WITHIN GROUP (ORDER BY T.SORT_ORDER)
           FROM REG_INFO_TARGET T
          WHERE T.REG_INFO_ID = I.REG_INFO_ID AND T.TARGET_TYPE = 'REGULATION')    AS REGULATION_TXT,
        (SELECT LISTAGG(T.TARGET_NM, ', ') WITHIN GROUP (ORDER BY T.SORT_ORDER)
           FROM REG_INFO_TARGET T
          WHERE T.REG_INFO_ID = I.REG_INFO_ID AND T.TARGET_TYPE = 'STANDARD')      AS STANDARD_TXT,
        (SELECT LISTAGG(T.TARGET_NM, ', ') WITHIN GROUP (ORDER BY T.SORT_ORDER)
           FROM REG_INFO_TARGET T
          WHERE T.REG_INFO_ID = I.REG_INFO_ID AND T.TARGET_TYPE = 'REGION')        AS REGION_TXT,
        (SELECT LISTAGG(T.TARGET_NM, ', ') WITHIN GROUP (ORDER BY T.SORT_ORDER)
           FROM REG_INFO_TARGET T
          WHERE T.REG_INFO_ID = I.REG_INFO_ID AND T.TARGET_TYPE = 'COUNTRY')       AS COUNTRY_TXT,
        (SELECT LISTAGG(T.TARGET_NM, ', ') WITHIN GROUP (ORDER BY T.SORT_ORDER)
           FROM REG_INFO_TARGET T
          WHERE T.REG_INFO_ID = I.REG_INFO_ID AND T.TARGET_TYPE = 'DIVISION')      AS DIVISION_TXT,
        (SELECT LISTAGG(T.TARGET_NM, ', ') WITHIN GROUP (ORDER BY T.SORT_ORDER)
           FROM REG_INFO_TARGET T
          WHERE T.REG_INFO_ID = I.REG_INFO_ID AND T.TARGET_TYPE = 'PRODUCT_GROUP') AS PRODUCT_GROUP_TXT,
        (SELECT LISTAGG(T.TARGET_NM, ', ') WITHIN GROUP (ORDER BY T.SORT_ORDER)
           FROM REG_INFO_TARGET T
          WHERE T.REG_INFO_ID = I.REG_INFO_ID AND T.TARGET_TYPE = 'PRODUCT')       AS PRODUCT_TXT,
        (SELECT COUNT(*) FROM REG_CONFLICT_HIST C
          WHERE C.NEW_REG_INFO_ID = I.REG_INFO_ID
             OR C.EXIST_REG_INFO_ID = I.REG_INFO_ID)                               AS CONFLICT_CNT
  FROM  REG_INFO I
 WHERE  I.USE_YN = 'Y';


-- ---------------------------------------------------------------------
-- 충돌 후보 1차 필터 (DB단)
--   같은 분야 + 같은 규제를 공유하는 레코드만 뽑아온 뒤,
--   계층 전개/포함관계 판정은 애플리케이션에서 수행한다.
--   (권역→국가 전개가 공통코드 계층 조회를 타므로 SQL 단독 판정은 비효율)
-- ---------------------------------------------------------------------
-- SELECT DISTINCT I.REG_INFO_ID, I.REG_NO, I.TITLE
--   FROM REG_INFO I
--   JOIN REG_INFO_TARGET T ON T.REG_INFO_ID = I.REG_INFO_ID
--  WHERE I.STATUS_CD <> 'EXPIRED'
--    AND I.FIELD_CD  = :fieldCd
--    AND T.TARGET_TYPE = 'REGULATION'
--    AND T.TARGET_CD IN (:regulationCds)
--    AND I.REG_INFO_ID <> NVL(:regInfoId, -1);
